### ISSUE TITLE
Add a LICENSE file

### ISSUE THREAD

**Issue by xobs** [lawrie/fpga_pio#2]
This project has been super useful in helping me to understand how the PIO blocks work. I'd like to use it in other projects, but I'd like to make sure that I don't run afoul of any licensing issues.

Would you mind adding a license to this project? I can create a PR if you've got one in mind.

**Comment by lawrie** [comment]
Hi @xobs, I have added a BSD LICENSE.

I have just replied to the other open issue on what I can remember about what is wrong or incomplete about this implementation.

Which is:

- I think there is an error in autopull/autopush where an extra cycle is being used that shouldn't be
- Merging the results of multiple state machines to produce the output pin state is not implemented
- Combining Fifos together to produce a deeper Fifo is not implemented

There were various aspects of the implementation that I was not very happy with, so I am sure that it can be improved a lot.

**Comment by xobs** [comment]
Looks good to me. Thanks!
